<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OOAJ2R4" failures="1" tests="4" name="InvocationTimeOutTest" time="6.258" errors="0" timestamp="2021-05-14T10:54:01 IST">
  <testcase classname="keyWords.A9_InvocationTimeOutTest" name="login" time="5.184">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method keyWords.A9_InvocationTimeOutTest.login() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method keyWords.A9_InvocationTimeOutTest.login() didn't finish within the time-out 5000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="keyWords.A9_InvocationTimeOutTest" name="search" time="0.675"/>
  <testcase classname="keyWords.A9_InvocationTimeOutTest" name="booking" time="0.209"/>
  <testcase classname="keyWords.A9_InvocationTimeOutTest" name="cancel" time="0.017"/>
</testsuite> <!-- InvocationTimeOutTest -->
